# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "MENAT GDG Summit 2014"
email: "team@gdgeskisehir.org"
description: "MENAT GDG Summit is an event organized by Google for GDG members of 20 countries in the MENAT region"
baseurl: ""
url: "http://summit.gdg-menat.com/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-israel.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Google"
organizerAlternateName: "Google Inc."
organizerDescription: "Founded in 1998, Google is a global technology leader focused on improving the ways people connect with information."
organizerEmail: "team@gdgeskisehir.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, summit, menat, google, programming, android, polymer, chrome, developers, istanbul"
twitterAccount: "@Google"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "MENAT GDG Summit <typeout> 2014"
eventDate: "December 3-4, 2014"
typeoutTextValues: '"", "Season", "Algeria", "Bahrain", "Egypt", "Iran", "Iraq", "Israel", "Jordan", "Kuwait", "Lebanon", "Yemen", "United Arab Emirates", "Libya", "Morocco", "Oman", "Palestine", "Qatar", "Saudi Arabia", "Syria", "Tunisia", "Turkey"'
typeoutFallback: "GDG Summit"

# About Block
aboutTitle: "About MENAT GDG Summit"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the region carefully crafted for you by Google and GDG community! Awesome speakers and lot's of fun!" }
  - {title: "Tech talks", image: "hackathon.jpg", text: "Full-day free-style hackaton! Want some real teambuilding on friday? Grab your team and join our hackathon!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "150", specialCharacter: "+", info: "attendees", detail: "from MENAT"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from everywhere"}
 - {count: "1,000,000", specialCharacter: "", info: "smiles", detail: "because it's that important to meet people in real life"}

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "SALT Galata"
eventLocationLink: "http://saltonline.org/"
eventStreetAddress: "Bankalar Caddesi 11, Karak√∂y"
eventAddressLocality: "Istanbul"
eventAddressLocalityRegion: "Istanbul"
eventPostalCode: "34420"
eventAddressCountry: "Turkey"
eventStartTime: "2014-12-3T9:00"
eventDoorTime: "08:00"
eventEndTime: "2014-12-4T20:00"
eventPlaceCoordinates: "41.0241794, 28.9717303"
mapCenterCoordinates: "41.0241794, 28.9717303"
mapMobileCenterCoordinates: "41.0241794, 28.9717303"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "SALT Galata"
venueFeatures: ["Beautiful cultural place", "Innovative venue", "Located in the historic Ottoman Bank on Bankalar Caddesi"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "gdgsummit", "menat"
twitterFeed: "https://www.googleapis.com/plus/v1/activities?query=%23menat+%23gdgsummit&key=AIzaSyBKc7cOtPZ6y1UzmQSadHzGIXzPhIfFFaY"

# Partners Block
organizersTitle: "Organizers"

# Footer
socialLinks:
 - {link: "https://plus.google.com/+Google", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=Google", icon: "twitter"}
 - {link: "https://www.facebook.com/Google", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://developers.google.com", text: "Google Developers"}
   - {link: "https://developers.google.com/groups", text: "Google Developer Groups"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:team@gdgeskisehir.org", text: "Event organizers"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms - from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "41.0241794, 28.9717303"
logisticsMapMobileCenterCoordinates: "41.0241794, 28.9717303"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Istanbul"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
